[build-system]
requires = ["setuptools", "wheel"]
[project]
name = "deutils"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pandas"]

[project.optional-dependencies]
test = ["pytest>=8.3.3"]
dev = ["deutils[test]"]
